CREATE TABLE `sbr402_warehouse_consolidation_carriers` (
  `LOCATION_ID` int(11) DEFAULT NULL,
  `LOCATION_NAME` varchar(50) DEFAULT NULL,
  `TRACKING_REQUIRED` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;
