CREATE TABLE `sbr402_warehouse_consolidation_locations` (
  `LOCATION_ID` int(11) DEFAULT NULL,
  `LOCATION_NAME` varchar(50) DEFAULT NULL,
  `TRACKING_REQUIRED` int(11) DEFAULT NULL,
  `LOCATION_TYPE` varchar(50) DEFAULT NULL,
  `LOCATION_COLUMN` int(11) DEFAULT NULL,
  `LOCATION_LEVEL` int(11) DEFAULT NULL,
  `CAPACITY` int(11) DEFAULT NULL,
  `SHIP_TO_HELD` varchar(50) DEFAULT NULL,
  `CARTONS_HELD` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




